language: java
# skip the default installation phase
install: true

branches:
  only:
    - master

addons:
  sonarcloud:
    organization: "thbingen"

# disable shallow clone so sonar won't get messed up
git:
  depth: false

script:
  # clean, run sonar, generate javadoc jar
  - mvn clean verify sonar:sonar javadoc:jar
  # sonar quality gate breaker
  - mvn --batch-mode --update-snapshots --non-recursive de.qaware.tools.sonarqube-build-breaker:sqbb-maven-plugin:sqbb -Dsqbb.projectKey=ADCL -Dsqbb.sonarQubeUrl=https://sonarcloud.io -Dsqbb.sonarQubeToken=$SONAR_TOKEN

before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name adclTeam
  - git config --local user.email adclTeam@gmail.com
  - export TRAVIS_TAG=${TRAVIS_TAG:-Build$TRAVIS_BUILD_NUMBER}
  - git tag "$TRAVIS_TAG"

deploy:
  # Deploying to GitHub Releases
  provider: releases
  api_key:
    secure: eSuPEfuc9U+ZSibstvQRgF2E/kHFoDOzQuzMHuy5IGyTkfKvanJ8tsGC/nJkZOnAc80i01K9oKtVgnXOE0Wb0yQqtRtAmIts4XNDfd9Ri2kYoaEMk+Xru+zx5yvrAnk0MQkvkOHHbMyWFWTy2pLckjG+gK2FQOWx4aNUkDlguenCoYkaSR6RDimf9f/yoYhBcYUbmzGxMPxNoA8UK68ogns9iOo61ffKxG5pxW66/09PjRbS+CWs10drXAKsVQqzZTDoVtwxXLWAjAyUg2RFXN9RRzBuUdy89iNHCBg72LLm6K3ND/N91Wb7Ae7YBd67Lca1zLqNEb5r9gqAidGKYi31ntJ3y5DQ27x2V+M954+vQq26i5Uonqc5hdU019KPZKilkmGvzVKskgylLWhXmMCvnoojR6fT06debLrxI6qf0kvt/SAwC6tvVotMRvjBCXQ3VhxsrF+wEEcWxGWqCGkpsi3ouSQgKGzI34OSAt35sejRcO01WPUdpkJ8O+5mRt4iGYX4Wd/dBo2HK4q+JcPBs+Vofn1LYpPx1LSYbx/3gDGNDUPagBVXSAAohU01eA4m5h3EHue1AlVTl2fJX8xUB+pbtZjF25UPGauAZET/ktxtD/74804VP766OQdKvzHWsqqV6Q65EaC3e0BoZ1WxNDSDLaxrqkRizsy0P74=
  file_glob: true
  # JAR, JavaDoc JAR and Sources JAR
  file: target/*.jar
  skip_cleanup: true

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
