language: java
# skip the default installation phase
install: true

#branches:
#  only:
#    - master

addons:
  sonarcloud:
    organization: "thbingen"

# disable shallow clone so sonar won't get messed up
git:
  depth: false

env:
  - NEO4J_CONF=/home/travis/build/qaware/adcl/nconf

before_script:
  #install neo4j
  - wget -O - https://debian.neo4j.org/neotechnology.gpg.key | sudo apt-key add -
  - echo 'deb https://debian.neo4j.org/repo stable/' | sudo tee -a /etc/apt/sources.list.d/neo4j.list
  - sudo apt-get update
  - sudo apt-get install neo4j=1:3.5.13
  - mkdir nconf
  - cp /etc/neo4j/neo4j.conf ./nconf
  - echo "dbms.security.auth_enabled=false" >> ./nconf/neo4j.conf
  - sudo neo4j start

script:
  # clean, run sonar, generate javadoc jar
  - mvn clean verify sonar:sonar javadoc:jar
  # sonar quality gate breaker
  - mvn --batch-mode --update-snapshots --non-recursive de.qaware.tools.sonarqube-build-breaker:sqbb-maven-plugin:sqbb -Dsqbb.projectKey=ADCL -Dsqbb.sonarQubeUrl=https://sonarcloud.io -Dsqbb.sonarQubeToken=$SONAR_TOKEN

before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name adclTeam
  - git config --local user.email adclTeam@gmail.com
  - export TRAVIS_TAG=${TRAVIS_TAG:-Build$TRAVIS_BUILD_NUMBER}
  - git tag "$TRAVIS_TAG"

deploy:
  # Deploying to GitHub Releases
  provider: releases
  api_key:
    secure: byZuGEwraQcoLfpHRShhkyyIVb6FCeoil6ookoocxlrcPEtkHIIUk5l5KJxuOBe8eugvVcM0Xbh2pQUGFK1soXja05xLfp5bjOWmpGQHXemev4+ORc7bjpY3UrA9kyMGyWEA0h98CVmP/W3WQu2BT5S/A1jKGZfYiJAfCTX19JQi/Z3neYm+9UABOlsi1p8nWFXsiO8GGZ/1Mc8mwfwdPfXGehCopwtDnSyE2uywbH2aYilRQrm8n+/mFzcYq5Pypk8rD/AqAqZQilyrL28nM+i3BeHTz2lgPLAnOOb4nSQrQONRDUWBR7T9JTGIibibjPLsMhX6ncwPTyphSpiTHCzB7caEMtZomydokt2ds8PNrY9emXHUj5cRGIVlL65w4Z9w5bOCeoOvS0RM1s3quzBj9ooYt4mSz1UCPSCZuG80pQwFmhtSIcezfKRD0EyUpMYYn5k7letRzNZ/aybkszjwfDAOmJ0qe8gM2wA1kYcbl2qR2NasAapO/sb5i0y3ebk99DawdDigC0W+GjxQvmrmDXvGOiH3l9HVlLB+ICR7pZIh26VBv1n+fqxCkb7Og4OjB1SdWCH9WEu+W8AapMJ2lHALR9CsRVuGoFB76qy/myGMXcdj5NH0GkKR2/vYlDeMUUdRBMZC2mCH93C+WrULWVYCma7nZZ55umBD5Kg=
  file_glob: true
  # JAR, JavaDoc JAR and Sources JAR
  file: target/*.jar
  skip_cleanup: true

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
