language: java
# skip the default installation phase
install: true

branches:
  only:
    - master

addons:
  sonarcloud:
    organization: "thbingen"

# disable shallow clone so sonar won't get messed up
git:
  depth: false

script:
  - mvn clean verify sonar:sonar javadoc:jar
  - mvn --batch-mode --update-snapshots --non-recursive de.qaware.tools.sonarqube-build-breaker:sqbb-maven-plugin:sqbb -Dsqbb.projectKey=ADCL -Dsqbb.sonarQubeUrl=https://sonarcloud.io -Dsqbb.sonarQubeToken=$SONAR_TOKEN
  - |
    if [ $TRAVIS_PULL_REQUEST == "false" ]; then
    curl --output githubdeployer.jar -sL https://github.com/deregges/githubdeployer/releases/download/1.0.0/githubdeployer.jar
    export TRAVIS_TAG=${TRAVIS_TAG:-build$TRAVIS_BUILD_NUMBER}
    java -jar githubdeployer.jar org=qaware repo=adcl token=$GIT_TOKEN tag=$TRAVIS_TAG title=$TRAVIS_TAG artifact=./target prerelease=true
    else
    echo "Skipping deployment as we are on a PR"
    fi

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
