name: onMergePushMaster

on:
  push:
    branches: 
    - master
  pull_request:
    branches:
    - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@latest
    - uses: actions/setup-java@latest
      with:
        java-version: '11.x'

    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@v1.1
